
// Promesas
const somethingWillHappen = () =>{ // Funci贸n de promesa
    return new Promise((resolve, reject) =>{ // return de nueva promesa con dos argumentos
        if (false){ // validaci贸n para ejecutar resolve o reject
            resolve('Hey!'); // Si es true, ejecuta el resolve
        } else {
            reject('Upsss!'); // Si es false ejecuta el reject
        }
    });
};

// Ejecutando funci贸n
somethingWillHappen()
    .then(response => console.log(response))
    .catch(err => console.error(err));



const somethingWillHappen2 = () =>{
    return new Promise((resolve, reject) => {
       if (false) {
           setTimeout(() => {
               resolve('True');
           }, 3000)
       } else {
           const error = new Error('Whoops!');
           reject(error);
       }
    });
}

//Ejecutando la funci贸n
somethingWillHappen2()
    .then(response => console.log(response)) //
    .catch(err => console.log(err)); // Como vasmos a controlar el error


// Correr varias promesas al mismo tiempo Promise.All
Promise.all([somethingWillHappen(), somethingWillHappen2])
    .then(response =>{
        console.log('Array of results', response);
    })

    .catch(err =>{
        console.error(err);
    })